### ISSUE TITLE
Change image tag/digest only

### ISSUE THREAD

**Issue by bluebrown** [bluebrown/kobold#19]
Currently, kobold updates the full image ref. This leads to the default registry being added to image for non fully qualified domain names. It would be better if only the tag / digest would be changed.

https://github.com/bluebrown/kobold/blob/main/internal/krm/krm.go#L210

**Comment by bluebrown** [comment]
maybe using https://github.com/distribution/distribution/blob/main/reference/reference.go to parse image refs, could help. Also with the default registry situation, which is a bit confusing atm.

**Comment by rossigee** [comment]
How would we like to do this?

So, currently, by default, we only support full image URIs like this...

```
image: test.azurecr.io/nginx # kobold: tag: latest; type: exact
```

Would something like the following work to support parts?

```
image:
  repository: ...
  tag: "1.0" # kobold: tag: ^1; type: semver; part: tag
  digest: "" # kobold: tag: ^1: type: semver; part: digest
```
