### ISSUE TITLE
allow dynamic krm selector expression to select image node

### ISSUE THREAD

**Issue by bluebrown** [bluebrown/kobold#3]
Currently there is a set of pre configured imageNodeResolvers: https://bluebrown.github.io/kobold/configuration/file-associations.html#file-associations.

It could be possible to allow the user to specify custom selectors to resolve image nodes.

For this the [PathMatcher](https://github.com/kubernetes-sigs/kustomize/blob/ee3f506d10d076412a5eeefd3dc8a471a2483413/kyaml/yaml/match.go#L21) can be used.

```go
yaml.PathMatcher{ Path: utils.SmarterPathSplitter(customPath, ".")}
```

The user would provide a glob to match filenames and a set of path selectors to resolve image nodes for matched files.

```yaml
imageNodeResolvers:
  - name: compose 
    match: *compose*.y?ml
    selectors:
      -  services.*.image

  - name: kube 
    match: *.yaml
    selectors:
      -  spec.template.spec.containers.*.image
```
